sudo: required
services:
  - docker

before_install: 
  - docker build -t mykitazolov/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run -e CI=true mykitazolov/react-test npm test
  # - docker run mykitazolov/react-test npm test -- --coverage

after_success:
  - docker build -t mykitazolov/multi-client ./client
  - docker build -t mykitazolov/multi-nginx ./nginx
  - docker build -t mykitazolov/multi-server ./server
  - docker build -t mykitazolov/multi-worker ./worker 
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push mykitazolov/multi-client
  - docker push mykitazolov/multi-nginx
  - docker push mykitazolov/multi-server
  - docker push mykitazolov/multi-worker